-- MySQL Script generated by MySQL Workbench
-- Mon Jun  3 18:49:53 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema PhotoPortal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PhotoPortal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PhotoPortal` DEFAULT CHARACTER SET utf8 ;
USE `PhotoPortal` ;

-- -----------------------------------------------------
-- Table `PhotoPortal`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PhotoPortal`.`USER` (
  `USER_ID` INT NOT NULL,
  `NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`USER_ID`),
  UNIQUE INDEX `USER_ID` (`USER_ID` ASC) INVISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PhotoPortal`.`PHOTO_POST`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PhotoPortal`.`PHOTO_POST` (
  `POST_ID` INT NOT NULL,
  `DESCRIPTION` VARCHAR(1000) NOT NULL,
  `CREATION_DATE` VARCHAR(45) NOT NULL,
  `PHOTO_LINK` VARCHAR(45) NOT NULL,
  `USER_ID` INT NOT NULL,
  PRIMARY KEY (`POST_ID`),
  INDEX `USER_ID` (`USER_ID` ASC) VISIBLE,
  CONSTRAINT `USER_ID`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `PhotoPortal`.`USER` (`USER_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `PhotoPortal`.`USER`
-- -----------------------------------------------------
START TRANSACTION;
USE `PhotoPortal`;
INSERT INTO `PhotoPortal`.`USER` (`USER_ID`, `NAME`) VALUES (1, 'masha');
INSERT INTO `PhotoPortal`.`USER` (`USER_ID`, `NAME`) VALUES (2, 'den');
INSERT INTO `PhotoPortal`.`USER` (`USER_ID`, `NAME`) VALUES (3, 'lia');
INSERT INTO `PhotoPortal`.`USER` (`USER_ID`, `NAME`) VALUES (4, 'sasha');
INSERT INTO `PhotoPortal`.`USER` (`USER_ID`, `NAME`) VALUES (5, 'kirill');
INSERT INTO `PhotoPortal`.`USER` (`USER_ID`, `NAME`) VALUES (6, 'lana');
INSERT INTO `PhotoPortal`.`USER` (`USER_ID`, `NAME`) VALUES (7, 'gleb');
INSERT INTO `PhotoPortal`.`USER` (`USER_ID`, `NAME`) VALUES (8, 'vera');
INSERT INTO `PhotoPortal`.`USER` (`USER_ID`, `NAME`) VALUES (9, 'anna');
INSERT INTO `PhotoPortal`.`USER` (`USER_ID`, `NAME`) VALUES (10, 'nikolai');

COMMIT;


-- -----------------------------------------------------
-- Data for table `PhotoPortal`.`PHOTO_POST`
-- -----------------------------------------------------
START TRANSACTION;
USE `PhotoPortal`;
INSERT INTO `PhotoPortal`.`PHOTO_POST` (`POST_ID`, `DESCRIPTION`, `CREATION_DATE`, `PHOTO_LINK`, `USER_ID`) VALUES (1, 'something', '2019-04-15 19:27:45', 'img1', 1);
INSERT INTO `PhotoPortal`.`PHOTO_POST` (`POST_ID`, `DESCRIPTION`, `CREATION_DATE`, `PHOTO_LINK`, `USER_ID`) VALUES (2, 'something new', '2019-04-15 19:28:45', 'img2', 1);
INSERT INTO `PhotoPortal`.`PHOTO_POST` (`POST_ID`, `DESCRIPTION`, `CREATION_DATE`, `PHOTO_LINK`, `USER_ID`) VALUES (3, 'something new new', '2019-04-15 20:27:45', 'img3', 2);
INSERT INTO `PhotoPortal`.`PHOTO_POST` (`POST_ID`, `DESCRIPTION`, `CREATION_DATE`, `PHOTO_LINK`, `USER_ID`) VALUES (4, 'something', '2019-04-16 19:27:45', 'img4', 3);
INSERT INTO `PhotoPortal`.`PHOTO_POST` (`POST_ID`, `DESCRIPTION`, `CREATION_DATE`, `PHOTO_LINK`, `USER_ID`) VALUES (5, 'something', '2019-04-17 19:27:45', 'img5', 3);
INSERT INTO `PhotoPortal`.`PHOTO_POST` (`POST_ID`, `DESCRIPTION`, `CREATION_DATE`, `PHOTO_LINK`, `USER_ID`) VALUES (6, 'something more new', '2019-04-09 19:27:45', 'img6', 4);
INSERT INTO `PhotoPortal`.`PHOTO_POST` (`POST_ID`, `DESCRIPTION`, `CREATION_DATE`, `PHOTO_LINK`, `USER_ID`) VALUES (7, 'something good', '2019-04-15 19:27:45', 'img7', 10);
INSERT INTO `PhotoPortal`.`PHOTO_POST` (`POST_ID`, `DESCRIPTION`, `CREATION_DATE`, `PHOTO_LINK`, `USER_ID`) VALUES (8, 'something more good', '2018-04-15 19:27:45', 'img8', 5);
INSERT INTO `PhotoPortal`.`PHOTO_POST` (`POST_ID`, `DESCRIPTION`, `CREATION_DATE`, `PHOTO_LINK`, `USER_ID`) VALUES (9, 'something very good', '2019-04-15 10:27:45', 'img9', 9);
INSERT INTO `PhotoPortal`.`PHOTO_POST` (`POST_ID`, `DESCRIPTION`, `CREATION_DATE`, `PHOTO_LINK`, `USER_ID`) VALUES (10, 'something sad', '2019-04-15 19:27:44', 'img10', 8);

COMMIT;

